[package]
name = 'obs-multi-rtmp-rs'
version = '0.1.0'
authors = ['progre <djyayutto@gmail.com>']
edition = '2018'

[dependencies]
once_cell = '1.5.2'

[lib]
name = 'rust'
crate-type = ['staticlib']
path = 'src-rs/lib.rs'
